# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yaroslav/oopLab/mms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yaroslav/oopLab/mms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/oopLab/mms/CMakeFiles /home/yaroslav/oopLab/mms//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/oopLab/mms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MemoryManagerInternal

# Build rule for target.
MemoryManagerInternal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemoryManagerInternal
.PHONY : MemoryManagerInternal

# fast build rule for target.
MemoryManagerInternal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/build
.PHONY : MemoryManagerInternal/fast

#=============================================================================
# Target rules for targets named MemoryManager

# Build rule for target.
MemoryManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemoryManager
.PHONY : MemoryManager

# fast build rule for target.
MemoryManager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManager.dir/build.make CMakeFiles/MemoryManager.dir/build
.PHONY : MemoryManager/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named ConsoleApplication

# Build rule for target.
ConsoleApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConsoleApplication
.PHONY : ConsoleApplication

# fast build rule for target.
ConsoleApplication/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleApplication.dir/build.make CMakeFiles/ConsoleApplication.dir/build
.PHONY : ConsoleApplication/fast

Console/console.o: Console/console.cpp.o
.PHONY : Console/console.o

# target to build an object file
Console/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleApplication.dir/build.make CMakeFiles/ConsoleApplication.dir/Console/console.cpp.o
.PHONY : Console/console.cpp.o

Console/console.i: Console/console.cpp.i
.PHONY : Console/console.i

# target to preprocess a source file
Console/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleApplication.dir/build.make CMakeFiles/ConsoleApplication.dir/Console/console.cpp.i
.PHONY : Console/console.cpp.i

Console/console.s: Console/console.cpp.s
.PHONY : Console/console.s

# target to generate assembly for a file
Console/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleApplication.dir/build.make CMakeFiles/ConsoleApplication.dir/Console/console.cpp.s
.PHONY : Console/console.cpp.s

MemoryManager/MemoryElements.o: MemoryManager/MemoryElements.cpp.o
.PHONY : MemoryManager/MemoryElements.o

# target to build an object file
MemoryManager/MemoryElements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryElements.cpp.o
.PHONY : MemoryManager/MemoryElements.cpp.o

MemoryManager/MemoryElements.i: MemoryManager/MemoryElements.cpp.i
.PHONY : MemoryManager/MemoryElements.i

# target to preprocess a source file
MemoryManager/MemoryElements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryElements.cpp.i
.PHONY : MemoryManager/MemoryElements.cpp.i

MemoryManager/MemoryElements.s: MemoryManager/MemoryElements.cpp.s
.PHONY : MemoryManager/MemoryElements.s

# target to generate assembly for a file
MemoryManager/MemoryElements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryElements.cpp.s
.PHONY : MemoryManager/MemoryElements.cpp.s

MemoryManager/MemoryManager.o: MemoryManager/MemoryManager.cpp.o
.PHONY : MemoryManager/MemoryManager.o

# target to build an object file
MemoryManager/MemoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManager.dir/build.make CMakeFiles/MemoryManager.dir/MemoryManager/MemoryManager.cpp.o
.PHONY : MemoryManager/MemoryManager.cpp.o

MemoryManager/MemoryManager.i: MemoryManager/MemoryManager.cpp.i
.PHONY : MemoryManager/MemoryManager.i

# target to preprocess a source file
MemoryManager/MemoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManager.dir/build.make CMakeFiles/MemoryManager.dir/MemoryManager/MemoryManager.cpp.i
.PHONY : MemoryManager/MemoryManager.cpp.i

MemoryManager/MemoryManager.s: MemoryManager/MemoryManager.cpp.s
.PHONY : MemoryManager/MemoryManager.s

# target to generate assembly for a file
MemoryManager/MemoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManager.dir/build.make CMakeFiles/MemoryManager.dir/MemoryManager/MemoryManager.cpp.s
.PHONY : MemoryManager/MemoryManager.cpp.s

MemoryManager/MemoryTable.o: MemoryManager/MemoryTable.cpp.o
.PHONY : MemoryManager/MemoryTable.o

# target to build an object file
MemoryManager/MemoryTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryTable.cpp.o
.PHONY : MemoryManager/MemoryTable.cpp.o

MemoryManager/MemoryTable.i: MemoryManager/MemoryTable.cpp.i
.PHONY : MemoryManager/MemoryTable.i

# target to preprocess a source file
MemoryManager/MemoryTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryTable.cpp.i
.PHONY : MemoryManager/MemoryTable.cpp.i

MemoryManager/MemoryTable.s: MemoryManager/MemoryTable.cpp.s
.PHONY : MemoryManager/MemoryTable.s

# target to generate assembly for a file
MemoryManager/MemoryTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemoryManagerInternal.dir/build.make CMakeFiles/MemoryManagerInternal.dir/MemoryManager/MemoryTable.cpp.s
.PHONY : MemoryManager/MemoryTable.cpp.s

Test/test.o: Test/test.cpp.o
.PHONY : Test/test.o

# target to build an object file
Test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Test/test.cpp.o
.PHONY : Test/test.cpp.o

Test/test.i: Test/test.cpp.i
.PHONY : Test/test.i

# target to preprocess a source file
Test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Test/test.cpp.i
.PHONY : Test/test.cpp.i

Test/test.s: Test/test.cpp.s
.PHONY : Test/test.s

# target to generate assembly for a file
Test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Test/test.cpp.s
.PHONY : Test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ConsoleApplication"
	@echo "... MemoryManager"
	@echo "... MemoryManagerInternal"
	@echo "... test"
	@echo "... Console/console.o"
	@echo "... Console/console.i"
	@echo "... Console/console.s"
	@echo "... MemoryManager/MemoryElements.o"
	@echo "... MemoryManager/MemoryElements.i"
	@echo "... MemoryManager/MemoryElements.s"
	@echo "... MemoryManager/MemoryManager.o"
	@echo "... MemoryManager/MemoryManager.i"
	@echo "... MemoryManager/MemoryManager.s"
	@echo "... MemoryManager/MemoryTable.o"
	@echo "... MemoryManager/MemoryTable.i"
	@echo "... MemoryManager/MemoryTable.s"
	@echo "... Test/test.o"
	@echo "... Test/test.i"
	@echo "... Test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

